### ISSUE TITLE
Desenhar Design do site

### ISSUE THREAD

**Issue by GustavoHonda** [codesnifferai/web#1]
Desenhar como ficarão as páginas Home, code, smells, e Rest API.

**Comment by pedrolucasrsc** [comment]
Hoje eu comecei a prototipar em .pdf as páginas. Também continuei o projeto no Figma:
[Protótipo_230912_084358.pdf](https://github.com/codesnifferai/web/files/12590496/Prototipo_230912_084358.pdf)
[https://www.figma.com/file/EyUN7TjAU4lvMjnJvR8ZBa/Codesnifferai?type=design&node-id=0-1&mode=design&t=ogJRq7vuqfqYZWfC-0](url)
